name: Deploy site

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install bun
        uses: oven-sh/setup-bun@v1


      - name: 🔨 Build Project
        run: |
          bun install
          bun run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          local-dir: dist/
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}